apiVersion: apps/v1
kind: Deployment
metadata:
  name: strapi
  namespace: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strapi
  template:
    metadata:
      labels:
        app: strapi
    spec:
      containers:
        - name: strapi
          image: ghcr.io/atakowiec/strapi-app:latest
          ports:
            - containerPort: 1337
          env:
            - name: NODE_ENV
              value: production
            - name: DATABASE_CLIENT
              value: mysql
            - name: DATABASE_HOST
              value: mysql
            - name: DATABASE_PORT
              value: "3306"
            - name: DATABASE_NAME
              value: strapi
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: strapi-db-secret
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: strapi-db-secret
                  key: password
          volumeMounts:
            - mountPath: /app/public/uploads
              name: uploads
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: strapi-uploads-pvc
