apiVersion: apps/v1
kind: Deployment
metadata:
  name: strapi
  namespace: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strapi
  template:
    metadata:
      labels:
        app: strapi
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: strapi
          image: ghcr.io/atakowiec/portfolio-strapi:latest
          ports:
            - containerPort: 1337
          env:
            - name: NODE_ENV
              value: production
            - name: DATABASE_CLIENT
              value: mysql
            - name: DATABASE_HOST
              value: mysql
            - name: DATABASE_PORT
              value: "3306"
            - name: DATABASE_NAME
              value: strapi
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: strapi-db-secret
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: strapi-db-secret
                  key: password
            - name: ADMIN_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: strapi-secrets
                  key: admin_jwt_secret
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: strapi-secrets
                  key: jwt_secret
            - name: APP_KEYS
              valueFrom:
                secretKeyRef:
                  name: strapi-secrets
                  key: app_keys
            - name: API_TOKEN_SALT
              valueFrom:
                secretKeyRef:
                  name: strapi-secrets
                  key: api_token_salt
            - name: TRANSFER_TOKEN_SALT
              valueFrom:
                secretKeyRef:
                  name: strapi-secrets
                  key: transfer_token_salt
            - name: ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: strapi-secrets
                  key: encryption_key
          volumeMounts:
            - mountPath: /app/public/uploads
              name: uploads
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: strapi-uploads-pvc
